# Generated by Django 4.1.5 on 2023-01-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_field1_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emailfield',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
